parameters:
  name: ""
  displayName: ""
  clusterType: ""
  clusterName: ""
  vmSize: ""
  k8sVersion: ""
  dependsOn: ""

stages:
  - stage: ${{ parameters.clusterName }}
    displayName: ${{ parameters.displayName }} - Create Cluster
    dependsOn:
      - ${{ parameters.dependsOn }}
      - setup
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
    jobs:
      - template: ../../templates/create-cluster.yaml
        parameters:
          name: ${{ parameters.name }}
          displayName: ${{ parameters.displayName }}
          clusterType: ${{ parameters.clusterType }}
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          vmSize: ${{ parameters.vmSize }}
          k8sVersion: ${{ parameters.k8sVersion }}
          dependsOn: ${{ parameters.dependsOn }}
          region: $(REGION_AKS_CLUSTER_TEST)
      - template: ../../templates/add-windows-nodepool-job.yaml
        parameters:
          depend: ${{ parameters.name }}
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          vmSize: ${{ parameters.vmSize }}

  - stage: ${{ parameters.name }}
    displayName: E2E - ${{ parameters.displayName }}
    dependsOn:
    - setup
    - publish
    - ${{ parameters.clusterName }}
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
      GOPATH: "$(Agent.TempDirectory)/go" # Go workspace path
      GOBIN: "$(GOPATH)/bin" # Go binaries path
      modulePath: "$(GOPATH)/src/github.com/Azure/azure-container-networking"
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    jobs:
      - job: ${{ parameters.name }}_windows
        displayName: Azure Stateless CNI Overlay Test Suite | Windows - (${{ parameters.name }})
        timeoutInMinutes: 120
        # error handled by warning-handler job below
        continueOnError: true
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
          demands:
          - agent.os -equals Linux
          - Role -equals $(CUSTOM_E2E_ROLE)
        steps:
          - template: ../../templates/windows-overlay-e2e-step-template.yaml
            parameters:
              name: ${{ parameters.name }}
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              cniType: stateless
              validateCniType: stateless
              testLoadArgs: "INSTALL_AZURE_VNET_STATELESS=true VALIDATE_V4OVERLAY=true"
              runWireserverTests: "true"
          - template: ../../templates/k8s-e2e-step-template.yaml
            parameters:
              sub: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: windows
              datapath: true
              dns: true
              portforward: true
              hostport: true
              service: true
              hybridWin: true

      # can only succeed with issues in windows
      - template: ../../templates/warning-handler-job-template.yaml
        parameters:
          dependsOnToEmitWarning: ${{ parameters.name }}_windows
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          fileSearchPattern: "azure-vnet*.log"
          # known windows issues that occur only in testing:
          # - windows blue screens and writes null characters to the statefile, making it unrecoverable
          # - the hns network gets deleted outside of the cni's control, so it still thinks the network exists
          searchPattern: "\\x00|\\\\x00|hcnOpenNetwork failed in Win32: The network was not found"
          cni: cniv2
          os: windows

      - job: failedE2ELogs_windows
        displayName: "Windows Failure Logs"
        dependsOn:
          - ${{ parameters.name }}_windows
        condition: in(dependencies.${{ parameters.name }}_windows.result, 'Failed', 'SucceededWithIssues')
        steps:
          - template: ../../templates/log-template.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: windows
              cni: cniv2
