# {{.RENDER_MSG}}
# SOURCE: {{.SRC}}
ARG ARCH
ARG OS

# {{.GO_IMG}}
FROM --platform=linux/${ARCH} {{.GO_PIN}} AS go

FROM go AS azure-ip-masq-merger
ARG OS
ARG VERSION
WORKDIR /azure-ip-masq-merger
COPY ./azure-ip-masq-merger .
RUN GOOS=$OS CGO_ENABLED=0 go build -a -o /go/bin/ip-masq-merger -trimpath -ldflags "-s -w -X main.version="$VERSION"" -gcflags="-dwarflocationlists=true" .

FROM scratch AS linux
COPY --from=azure-ip-masq-merger /go/bin/ip-masq-merger azure-ip-masq-merger
ENTRYPOINT [ "/azure-ip-masq-merger" ]
