parameters:
  - name: name
    type: string
    default: ""
  - name: displayName
    type: string
    default: ""
  - name: clusterType
    type: string
    default: ""
  - name: clusterName
    type: string
    default: ""
  - name: vmSize
    type: string
    default: ""
  - name: k8sVersion
    type: string
    default: ""
  - name: dependsOn
    type: object
    default: ""
  - name: os
    type: string
    default: ""
  - name: scaleup
    type: string
    default: ""

stages:
  - stage: ${{ parameters.clusterName }}
    displayName: ${{ parameters.displayName }} - Create Cluster
    condition: or(
        eq('${{ parameters.os }}', 'linux'),
        and(eq('${{ parameters.os }}', 'windows'), eq(dependencies.setup.outputs['env.GitDiffCheck.RunWindowsTests'], 'true'))
      )
    dependsOn:
      - ${{ parameters.dependsOn }}
      - setup
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
      runWindowsTest: $[ stagedependencies.setup.env.outputs['GitDiffCheck.RunWindowsTests'] ]
    jobs:
      - template: ../../templates/create-cluster.yaml
        parameters:
          name: ${{ parameters.name }}
          displayName: ${{ parameters.displayName }}
          clusterType: ${{ parameters.clusterType }}
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          vmSize: ${{ parameters.vmSize }}
          vmSizeWin: ${{ parameters.vmSize }}
          k8sVersion: ${{ parameters.k8sVersion }}
          dependsOn: ${{ parameters.dependsOn }}
          os: ${{ parameters.os }}
          region: $(REGION_DUALSTACKOVERLAY_CLUSTER_TEST) # Dualstack has a specific region requirement
  - stage: ${{ parameters.name }}
    displayName: E2E-${{ parameters.displayName }}
    dependsOn:
    - setup
    - publish
    - ${{ parameters.clusterName }}
    variables:
      GOPATH: "$(Agent.TempDirectory)/go" # Go workspace path
      GOBIN: "$(GOPATH)/bin" # Go binaries path
      modulePath: "$(GOPATH)/src/github.com/Azure/azure-container-networking"
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    jobs:
      - job: ${{ parameters.name }}_${{ parameters.os }}
        displayName: DualStack Overlay Test Suite | ${{ parameters.os }} - (${{ parameters.name }})
        timeoutInMinutes: 120
        # error handled by warning-handler job below
        continueOnError: ${{ eq(parameters.os, 'windows') }}
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
          demands:
          - agent.os -equals Linux
          - Role -equals $(CUSTOM_E2E_ROLE)
        steps:
          - ${{ if eq(parameters.os, 'linux') }}:
            - template: dualstackoverlay-e2e-step-template.yaml
              parameters:
                name: ${{ parameters.name }}
                clusterName: ${{ parameters.clusterName }}-$(commitID)
                os: ${{ parameters.os }}
                scaleup: ${{ parameters.scaleup }}
          - ${{ if eq(parameters.os, 'windows') }}:
            - template: ../../templates/windows-overlay-e2e-step-template.yaml
              parameters:
                name: ${{ parameters.name }}
                clusterName: ${{ parameters.clusterName }}-$(commitID)
                cniType: cniv2
                validateCniType: dualstack
                testLoadArgs: "INSTALL_DUALSTACK_OVERLAY=true VALIDATE_DUALSTACK=true"
                regionClusterTest: $(REGION_DUALSTACKOVERLAY_CLUSTER_TEST)
                scaleup: ${{ parameters.scaleup }}
          - template: ../../templates/k8s-e2e-step-template.yaml
            parameters:
              sub: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: ${{ parameters.os }}
              dualstack: ${{ eq(parameters.os, 'linux') }} # RUN IN LINUX not WINDOWS Currently broken for scenario and blocking releases, HNS is investigating. Covered by go test in E2E step template
              dns: true
              portforward: true
              service: ${{ eq(parameters.os, 'linux') }} # RUN IN LINUX NOT WINDOWS Currently broken for scenario and blocking releases, HNS is investigating.
              hostport: true
              hybridWin: ${{ eq(parameters.os, 'windows') }}

      # can only succeed with issues in windows
      - ${{ if eq(parameters.os, 'windows') }}:
        - template: ../../templates/warning-handler-job-template.yaml
          parameters:
            dependsOnToEmitWarning: ${{ parameters.name }}_${{ parameters.os }}
            clusterName: ${{ parameters.clusterName }}-$(commitID)
            fileSearchPattern: "azure-vnet*.log"
            # known windows issues that occur only in testing:
            # - windows blue screens and writes null characters to the statefile, making it unrecoverable
            # - the hns network gets deleted outside of the cni's control, so it still thinks the network exists
            searchPattern: "\\x00|\\\\x00|hcnOpenNetwork failed in Win32: The network was not found"
            cni: cniv2
            os: windows

      - job: failedE2ELogs_${{ parameters.os }}
        displayName: "${{ parameters.os }} Failure Logs"
        dependsOn:
          - ${{ parameters.name }}_${{ parameters.os }}
        condition: in(dependencies.${{ parameters.name }}_${{ parameters.os }}.result, 'Failed', 'SucceededWithIssues')
        steps:
          - template: ../../templates/log-template.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: ${{ parameters.os }}
              cni: cniv2

