//go:build longrunning_connectivity_test
// +build longrunning_connectivity_test

package longrunningcluster

import (
	"fmt"
	"os"
	"testing"

	"github.com/onsi/ginkgo"
	"github.com/onsi/gomega"
)

func TestLongRunningConnectivity(t *testing.T) {
	gomega.RegisterFailHandler(ginkgo.Fail)
	ginkgo.RunSpecs(t, "Long-Running Connectivity Suite")
}

var _ = ginkgo.Describe("Long-Running Connectivity Tests", func() {
	ginkgo.It("tests TCP connectivity between rotating and always-on pods in the same zone", func() {
		buildID := os.Getenv("BUILD_ID")
		if buildID == "" {
			ginkgo.Fail("Missing required environment variable: BUILD_ID")
		}

		zone := GetZone()
		if zone != "" {
			fmt.Printf("Running connectivity test for zone %s\n", zone)
		}

		kubeconfig := getKubeconfigPath("aks-1")

		rotatingNS := GetZonedRotatingNS(buildID)
		alwaysOnNS := GetZonedAlwaysOnNS(buildID)
		dsName := GetDaemonSetName()

		// Find the DaemonSet pod name (auto-generated by K8s)
		dsPodName := GetDaemonSetPodName(kubeconfig, alwaysOnNS, dsName)
		gomega.Expect(dsPodName).NotTo(gomega.BeEmpty(),
			fmt.Sprintf("DaemonSet pod not found for %s in namespace %s", dsName, alwaysOnNS))
		fmt.Printf("DaemonSet always-on pod: %s\n", dsPodName)

		// Find the rotating deployment's pod name (auto-generated by K8s)
		rotatingDeploymentName := GetRotatingPodName(0)
		rotatingPodName := GetDeploymentPodName(kubeconfig, rotatingNS, rotatingDeploymentName)
		gomega.Expect(rotatingPodName).NotTo(gomega.BeEmpty(),
			fmt.Sprintf("Rotating deployment pod not found for %s in namespace %s", rotatingDeploymentName, rotatingNS))
		fmt.Printf("Rotating deployment pod: %s (from deployment %s)\n", rotatingPodName, rotatingDeploymentName)

		// Test connectivity between rotating pod and DaemonSet pod (same VNet)
		connectivityTests := []ConnectivityTest{
			{
				Name:            "LR-Rotating-To-AlwaysOn-Z" + zone,
				SourcePod:       rotatingPodName,
				SourceNamespace: rotatingNS,
				DestinationPod:  dsPodName,
				DestNamespace:   alwaysOnNS,
				Cluster:         "aks-1",
				Description:     fmt.Sprintf("Zone %s: rotating pod -> DaemonSet pod (cx_vnet_v1/lr)", zone),
				ShouldFail:      false,
			},
			{
				Name:            "LR-AlwaysOn-To-Rotating-Z" + zone,
				SourcePod:       dsPodName,
				SourceNamespace: alwaysOnNS,
				DestinationPod:  rotatingPodName,
				DestNamespace:   rotatingNS,
				Cluster:         "aks-1",
				Description:     fmt.Sprintf("Zone %s: DaemonSet pod -> rotating pod (cx_vnet_v1/lr)", zone),
				ShouldFail:      false,
			},
		}

		ginkgo.By(fmt.Sprintf("Running %d long-running connectivity tests for zone %s", len(connectivityTests), zone))

		successCount := 0
		failureCount := 0

		for _, test := range connectivityTests {
			ginkgo.By(fmt.Sprintf("Test: %s - %s", test.Name, test.Description))

			err := RunConnectivityTest(test)

			if test.ShouldFail {
				if err == nil {
					fmt.Printf("Test %s: UNEXPECTED SUCCESS (expected to be blocked!)\n", test.Name)
					failureCount++
					ginkgo.Fail(fmt.Sprintf("Test %s: Expected failure but succeeded", test.Name))
				} else {
					fmt.Printf("Test %s: Correctly blocked\n", test.Name)
					successCount++
				}
			} else {
				if err != nil {
					fmt.Printf("Test %s: FAILED - %v\n", test.Name, err)
					failureCount++
					gomega.Expect(err).To(gomega.BeNil(), fmt.Sprintf("Test %s failed: %v", test.Name, err))
				} else {
					fmt.Printf("Test %s: Connectivity successful\n", test.Name)
					successCount++
				}
			}
		}

		ginkgo.By(fmt.Sprintf("Zone %s connectivity: %d succeeded, %d failures", zone, successCount, failureCount))
	})
})
