parameters:
  - name: dependsOn
    type: object
    default: ""
  - name: name
    type: string
    default: cilium_nodesubnet_e2e
  - name: displayName
    type: string
    default: ""
  - name: clusterType
    type: string
    default: nodesubnet-byocni-nokubeproxy-up
  - name: clusterName
    type: string
    default: cilndsubnete2e
  - name: vmSize
    type: string
    default: ""
  - name: os
    type: string
    default: linux
  - name: arch
    type: string
    default: ""
  - name: osSKU
    type: string
    default: Ubuntu
  - name: hubbleEnabled
    type: boolean
    default: false
  - name: dualstackVersion
    type: string
    default: ""
  - name: cni
    type: string
    default: cilium
  - name: scaleup
    type: string
    default: ""

stages:
  - stage: ${{ parameters.clusterName }}
    displayName: ${{ parameters.displayName }} - Create Cluster
    condition: and(succeeded(), eq(dependencies.setup.outputs['env.GitDiffCheck.RunCiliumTests'], 'true'))
    dependsOn:
      - ${{ parameters.dependsOn }}
      - setup
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
    jobs:
      - template: ../../templates/create-cluster.yaml
        parameters:
          name: ${{ parameters.name }}
          displayName: ${{ parameters.displayName }}
          clusterType: ${{ parameters.clusterType }}
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          vmSize: ${{ parameters.vmSize }}
          region: $(REGION_AKS_CLUSTER_TEST)

  - stage: ${{ parameters.name }}
    displayName: E2E-${{ parameters.displayName }}
    condition: and(succeeded(), eq(variables.TAG, variables.CURRENT_VERSION), eq(dependencies.setup.outputs['env.GitDiffCheck.RunCiliumTests'], 'true'))
    variables:
      TAG: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.Tag'] ]
      CURRENT_VERSION: $[ stagedependencies.containerize.check_tag.outputs['CurrentTagManifests.currentTagManifests'] ]
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
      GOPATH: "$(Agent.TempDirectory)/go" # Go workspace path
      GOBIN: "$(GOPATH)/bin" # Go binaries path
      modulePath: "$(GOPATH)/src/github.com/Azure/azure-container-networking"
    dependsOn:
      - setup
      - publish
      - ${{ parameters.clusterName }}
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    jobs:
      - job: ${{ parameters.name }}
        displayName: Nodesubnet with Cilium - (${{ parameters.name }})
        timeoutInMinutes: 120
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
          demands:
            - agent.os -equals Linux
            - Role -equals $(CUSTOM_E2E_ROLE)
        steps:
          - template: cilium-nodesubnet-e2e-step-template.yaml
            parameters:
              name: ${{ parameters.name }}
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              arch: ${{ parameters.arch }}
              os: ${{ parameters.os }}
              scaleup: ${{ parameters.scaleup }}
          - template: ../../templates/k8s-e2e-step-template.yaml
            parameters:
              sub: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: ${{ parameters.os }}
              datapath: true
              dns: true
              cni: cilium
              portforward: true
              service: true

      - job: failedE2ELogs
        displayName: "Failure Logs"
        dependsOn:
          - ${{ parameters.name }}
        condition: failed()
        steps:
          - template: ../../templates/log-template.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: ${{ parameters.os }}
              cni: cilium

