name: 'Docker Base Images'
on:
  workflow_dispatch:
  pull_request:
    types:
        - opened
        - reopened
        - synchronize
        - ready_for_review
  merge_group:
    types:
      - checks_requested

permissions:
  contents: read

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: go.mod
    - name: go env
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
    - name: Render Dockerfiles
      run: make dockerfiles
    - name: Fail if base images are outdated
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected. Please run 'make dockerfiles' locally to update the base images."
          exit 1
        fi
