name: crdgen
on:
  workflow_dispatch:
  pull_request:
    types:
        - opened
        - reopened
        - synchronize
        - ready_for_review
  merge_group:
    types:
      - checks_requested

permissions:
  contents: read

jobs:
  crdgen:
    name: CRDs are Generated
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: go.mod
    - name: Regenerate NodeNetworkConfig CRD
      run: make -C crd/nodenetworkconfig
    - name: Regenerate MultitenantNetworkContainer CRD
      run: make -C crd/multitenantnetworkcontainer
    - name: Regenerate Multitenancy CRDs
      run: make -C crd/multitenancy
    - name: Regenerate ClusterSubnetState CRD
      run: make -C crd/clustersubnetstate
    - name: Regenerate OverlayExtensionConfig CRD
      run: make -C crd/overlayextensionconfig
    - name: Fail if the tree is dirty
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected. Please run 'make regenerate-crd' locally to regenerate crds."
          exit 1
        fi
