apiVersion: v1
data:
  cns_config.json: |-
    {
      "CNIConflistFilepath": "/etc/cni/net.d/05-cilium.conflist",
      "CNIConflistScenario": "cilium",
      "ChannelMode": "CRD",
      "EnableAsyncPodDelete": true,
      "EnableCNIConflistGeneration": true,
      "EnableIPAMv2": false,
      "EnableK8sDevicePlugin": false,
      "EnableLoggerV2": false,
      "EnableStateMigration": false,
      "EnableSubnetScarcity": false,
      "EnableSwiftV1DualStack": false,
      "InitializeFromCNI": false,
      "ManageEndpointState": true,
      "ManagedSettings": {
        "InfrastructureNetworkID": "",
        "NodeID": "",
        "NodeSyncIntervalInSeconds": 30,
        "PrivateEndpoint": ""
      },
      "MetricsBindAddress": ":10092",
      "ProgramSNATIPTables": false,
      "TelemetrySettings": {
        "DebugMode": false,
        "DisableAll": false,
        "HeartBeatIntervalInMins": 30,
        "RefreshIntervalInSecs": 15,
        "SnapshotIntervalInMins": 60,
        "TelemetryBatchIntervalInSecs": 15,
        "TelemetryBatchSizeBytes": 16384
      }
    }
kind: ConfigMap
metadata:
  name: cns-config
  namespace: kube-system
