parameters:
  name: ""
  displayName: ""
  arch: ""
  os: ""
  clusterType: ""
  clusterName: ""
  vmSize: ""
  k8sVersion: ""
  os_version: ""
  scaleup: ""
  dependsOn: ""

stages:
  - stage: ${{ parameters.clusterName }}
    displayName: ${{ parameters.displayName }} - Create Cluster
    dependsOn:
      - ${{ parameters.dependsOn }}
      - setup
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
    jobs:
      - template: ../../templates/create-cluster.yaml
        parameters:
          name: ${{ parameters.name }}
          displayName: ${{ parameters.displayName }}
          clusterType: ${{ parameters.clusterType }}
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          vmSize: ${{ parameters.vmSize }}
          vmSizeWin: ${{ parameters.vmSize }} # Matching linux vmSize
          k8sVersion: ${{ parameters.k8sVersion }}
          dependsOn: ${{ parameters.dependsOn }}
          os: ${{ parameters.os }}
          region: $(REGION_AKS_CLUSTER_TEST)

  - stage: ${{ parameters.name }}
    displayName: E2E-${{ parameters.displayName }}
    variables:
      GOPATH: "$(Agent.TempDirectory)/go" # Go workspace path
      GOBIN: "$(GOPATH)/bin" # Go binaries path
      modulePath: "$(GOPATH)/src/github.com/Azure/azure-container-networking"
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
    dependsOn:
    - setup
    - publish
    - ${{ parameters.clusterName }}
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    jobs:
      - job: ${{ parameters.name }}
        displayName: Singletenancy AKS - (${{ parameters.name }})
        timeoutInMinutes: 120
        # continue on error only in linux case to workaround known cniv1 issue where we leak an ip
        # this occurs when the azure vnet ipam releases an ip from its statefile and sends a successful
        # delete response but the azure cni gets a broken pipe error and doesn't delete the ip from its
        # statefile. a symptom of this problem is 'Initializing HTTP client with connection timeout'
        # appearing in the logs, which is checked below
        continueOnError: ${{ eq(parameters.os, 'linux') }}
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
          demands:
          - agent.os -equals Linux
          - Role -equals $(CUSTOM_E2E_ROLE)
        steps:
          - template: e2e-step-template.yaml
            parameters:
              name: ${{ parameters.name }}
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              arch: ${{ parameters.arch }}
              os: ${{ parameters.os }}
              os_version: ${{ parameters.os_version }}
              scaleup: ${{ parameters.scaleup }}
      
      # can only succeed with issues in linux
      - template: ../../templates/warning-handler-job-template.yaml
        parameters:
          dependsOnToEmitWarning: ${{ parameters.name }}
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          fileSearchPattern: "azure-vnet*.log"
          searchPattern: "Initializing HTTP client with connection timeout"
          cni: cniv1
          os: ${{ parameters.os }}

      - template: ../../cni/k8s-e2e/k8s-e2e-job-template.yaml
        parameters:
          sub: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          os: ${{ parameters.os }}
          datapath: true
          dns: true
          portforward: true
          hybridWin: true
          service: true
          hostport: true
          dependsOn: ${{ parameters.name }}

      - job: failedE2ELogs
        displayName: "Failure Logs"
        dependsOn:
          - ${{ parameters.name }}
          - cni_${{ parameters.os }}
        condition: failed()
        steps:
          - template: ../../templates/log-template.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: ${{ parameters.os }}
              cni: cniv1
